Enable cppcheck lints in behavior_velocity_planner
tier4/Pilot.Auto pull request #159
Opened 2020-12-09 17:22 UTC by nnmm

I only fixed cppcheck lints and missing includes (for which I wrote a script), as well as clang-tidy lints. There was one about the `stop_point` variable in stop_line/scene.cpp being possibly uninitialized.

2020-12-10 02:54 UTC, jilaada requested changes
Great changes! Though I needed to make some modifications below in order to get it to work - Those are listed below so once those are done I am happy to merge. 

Just a quick question - running clang-tidy on a random sample of files yields some warnings generated. Are we not fixing the warnings?

2020-12-10 02:54 UTC, jilaada commented on planning/scenario_planning/lane_driving/behavior_planning/behavior_velocity_planner/include/utilization/interpolation/cubic_spline.hpp
> +// Copyright 2018 Forrest
This is another example which is the same as the #153 copyright issue.

2020-12-14 14:33 UTC, nnmm commented
@jilaada I made the change to package.xml – I think I had already changed it locally and didn't commit it for some reason.

2020-12-15 02:15 UTC, jilaada approved these changes
@nnmm Great! Thanks for adding that commit. I think for the copyright issue we can fix them in another PR as this is not the only instance

2020-12-15 02:16 UTC, merged