ported pose2twist from ROS1 to ROS2
tier4/Pilot.Auto pull request #19
Opened 2020-10-12 08:33 UTC by nik-tier4

This PR ports pose2twist from ROS1 to ROS2

Changes and notes I made during the port.

The naming of header files are all small letter in Ros2:
`<std_msgs/Float32.h> to <std_msgs/msg/float32.hpp>`
`geometry_msgs/PoseStamped.h to geometry_msgs/msg/pose_stamped.hpp`

2020-10-14 12:29 UTC, fred-apex-ai requested changes

2020-10-19 01:29 UTC, nik-tier4 commented on localization/twist_estimator/pose2twist/CMakeLists.txt
> +find_package(ament_cmake REQUIRED)
yes, updated it.

2020-10-19 01:43 UTC, nik-tier4 commented on localization/twist_estimator/pose2twist/include/pose2twist/pose2twist_core.h
>  #pragma once
never used linter before, so what is the change needed?

2020-10-20 11:21 UTC, fred-apex-ai reviewed
changes fix my comments. Thans

2020-10-20 13:11 UTC, mitsudome-r commented
@nik-tier4 Can you rebase your branch to newest ros2 branch?
```
git fetch origin
git rebase origin/ros2
```

2020-10-21 01:50 UTC, nik-tier4 reviewed
include guards fixed

2020-10-21 03:31 UTC, merged