adding linters to ekf_localizer
tier4/Pilot.Auto pull request #194
Opened 2020-12-14 08:02 UTC by nik-tier4

`cpp_lint` giving some errors related to TODO.

2020-12-14 09:59 UTC, esteve requested changes

2020-12-14 09:59 UTC, esteve commented on localization/pose_twist_fusion_filter/ekf_localizer/package.xml
> +  <test_depend>ament_cmake_cppcheck</test_depend>
No need to add `ament_cmake_cppcheck` as it's already part of `ament_lint_common`

2020-12-14 09:59 UTC, esteve commented on localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
> +  show_debug_info_ = declare_parameter("show_debug_info", static_cast<bool>(false));
This cast is not needed.

2020-12-14 09:59 UTC, esteve commented on localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
> +  ekf_rate_ = declare_parameter("predict_frequency", static_cast<double>(50.0));
Cast not needed here either.

2020-12-14 09:59 UTC, esteve commented on localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
> +  tf_rate_ = declare_parameter("tf_rate", static_cast<double>(10.0));
Cast

2020-12-14 09:59 UTC, esteve commented on localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp
> +    declare_parameter("enable_yaw_bias_estimation", static_cast<bool>(true));
Cast

2020-12-14 10:02 UTC, esteve commented
@nik-tier4 casts for parameters shouldn't be needed. As for the `TODO` in https://github.com/nik-tier4/Pilot.Auto/blob/add_linters_ekf_localizer/localization/pose_twist_fusion_filter/ekf_localizer/src/ekf_localizer.cpp#L324, `git blame` says it was @mitsudome-r who last modified that line. Could you add `TODO(mitsudome-r)` ? Thanks.

2020-12-15 01:36 UTC, nik-tier4 commented
@esteve all changes made. Kindly review it.

2020-12-15 15:06 UTC, esteve approved these changes
@nik-tier4 thanks for addressing my feedback.

2020-12-15 15:06 UTC, merged