ROS2 Linting: spline_interpolation
tier4/Pilot.Auto pull request #203
Opened 2020-12-15 07:53 UTC by jilaada

## Summary

Simple lint of the `spline_interpolation` package. Only changes were in package.xml where I fixed the indentation.

## Testing
1. Compile with the correct build flags
```
colcon build --packages-up-to spline_interpolation --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=1
```
2. Run the linter tests
```
colcon test --packages-select spline_interpolation && colcon test-result --verbose
```
3. Run clang-tidy on the the source files from the root AutowareArchitectureProposal directory
```
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/spline_interpolation/src/*
clang-tidy -p build/compile_commands.json src/autoware/autoware.iv/common/math/spline_interpolation/include/spline_interpolation/*
```

2020-12-15 15:11 UTC, esteve requested changes

2020-12-15 15:11 UTC, esteve commented on common/math/spline_interpolation/package.xml
> +	<name>spline_interpolation</name>
@jilaada could you revert the spaces-to-tabs changes? Thanks.

2020-12-16 09:03 UTC, esteve commented
@jilaada I've replaced 4-space indents with 2 spaces to match the other `package.xml` files in https://github.com/tier4/Pilot.Auto/pull/203/commits/4614be6aa04e349d80a6ffbb8210a462193d782b

2020-12-16 09:03 UTC, esteve approved these changes

2020-12-16 09:11 UTC, jilaada commented
> @jilaada I've replaced 4-space indents with 2 spaces to match the other `package.xml` files in [4614be6](https://github.com/tier4/Pilot.Auto/commit/4614be6aa04e349d80a6ffbb8210a462193d782b)

Ah thanks for making that change!

2020-12-16 10:02 UTC, merged

2020-12-16 10:03 UTC, esteve commented
@jilaada no problem! :slightly_smiling_face: